{{ $namespace := .Release.Namespace }}

{{- range until 10 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $namespace }}-api-group-issue-cm-{{ . }}
data:
  configmap.properties: |
    hello: world
{{- end }}
