{{ $namespace := .Release.Namespace }}

{{- range until 10 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $namespace }}-api-group-issue-deploy-{{ . }}
spec:
  selector:
    matchLabels:
      internal.symphony.com/name: api-group-issue
  template:
    metadata:
      labels:
        internal.symphony.com/name: api-group-issue
    spec:
      containers:
        - name: api-group-issue
          image: nginx
{{- end }}
